# -*- coding: utf-8 -*-
"""DataSplitter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BmCmzHZbakO0NzHLZLacXcvy3tr99ViQ

#Train Test Split w/ Force of the Known Robovetter Error
"""

# forcing the known Robovetter error to the test set, so we can easily pull its
# prediction from the model, without having to create another "blind" model
# that hasn't been tested on that observation

import pandas as pd
from sklearn.model_selection import train_test_split

def splitter(df, target_kepoi='K00242.01'):
    # Removing Robovetter Error
    target_obs = df[df.index == target_kepoi]
    remaining_data = df[df.index != target_kepoi]

    # normal TTS w/ 90% Train/10% Test (more train due to small sample)
    X_rem = remaining_data.drop(columns=['target', 'kepoi_name'])
    y_rem = remaining_data['target']
    X_train, X_test, y_train, y_test = train_test_split(X_rem, y_rem,
                                                        test_size=0.10,
                                                        random_state=42,
                                                        stratify=y_rem)
    # Join the Robovetter Error to Test Sets
    X_robo = target_obs.drop(columns=['target', 'kepoi_name'])
    y_robo = target_obs['target']
    X_test_pre = pd.concat([X_test, X_robo])
    y_test_final = pd.concat([y_test, y_robo])
    return X_train, X_test_pre, y_train, y_test_final

