# -*- coding: utf-8 -*-
"""DataInC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1STZcxJpRvpdhpqDrtv4Otxwu0Ni9GY2L

# Data Ingestion & Initial Cleaning
"""

import pandas as pd
from sklearn import set_config
from IPython.core.interactiveshell import InteractiveShell

def ingest_and_clean_data():
    # Function Ingests & Cleans the Data, producing kepler_clean dataframe
    set_config(display='text')
    InteractiveShell.ast_node_interactivity = "all"

    # Ingest Data
    file_id = '1W6vu5CMyIrz4RdoSCJq_OpzCZwOJ79Hv'
    url = f'https://drive.google.com/uc?id={file_id}'

    try:
        kepler_df = pd.read_csv(url)
    except Exception as e:
        print(f"Error loading data: {e}")
        return None

    # Asserting kepoi_name is unique
    assert kepler_df['kepoi_name'].is_unique, "(kepoi_name) is not unique"

    # Setting kepoi_name as index
    kepler_df.set_index('kepoi_name', inplace=True)

    # Feature selection based on domain knowledge and provided
    # feature descriptions from NASA
    base_features = ['koi_disposition', 'koi_period', 'koi_impact',
                     'koi_duration','koi_depth', 'koi_prad', 'koi_teq',
                     'koi_insol', 'koi_model_snr','koi_tce_plnt_num',
                     'koi_steff', 'koi_slogg', 'koi_srad', 'koi_kepmag']

    # Using a Regex to get the _err1 & _err2 columns from the dataframe as well
    pattern = '^' + '|^'.join(base_features)
    kepler_trim = kepler_df.filter(regex=pattern).copy()

    # Dropping fully NULL columns
    cols_to_drop = ['koi_teq_err1', 'koi_teq_err2']
    kepler_trim = kepler_trim.drop(columns=[c for c in cols_to_drop if c in kepler_trim.columns])

    # Dropping observations with any NULL values
    kepler_clean = kepler_trim.dropna().copy()

    print(f"Data Ingestion Complete. Shape: {kepler_clean.shape}")
    
    # Creating extra copy of the original dataframe for future Robovetter Eval
    robovetter_df = kepler_df.copy()

    return kepler_clean, robovetter_df
