# -*- coding: utf-8 -*-
"""FeatureEngineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FB1md6eOEW6G3y2pVSam-NyJESAdvGTw

# Feature Engineering & Preprocessing
"""

import pandas as pd
import numpy as np

def run_feature_pipeline(df):
    df_eng = df.copy()

    # Planet to Star Size Ratio
    SOLAR_TO_EARTH_RADIUS = 109.076
    df_eng['planet_star_rad_ratio'] = df_eng['koi_prad'] / (df_eng['koi_srad'] * SOLAR_TO_EARTH_RADIUS)

    def propagate_ratio_err(df, err_suffix):
        rel_err_prad = (df[f'koi_prad_{err_suffix}'] / df['koi_prad']).abs()
        rel_err_srad = (df[f'koi_srad_{err_suffix}'] / df['koi_srad']).abs()
        total_rel_err = np.sqrt(rel_err_prad**2 + rel_err_srad**2)
        multiplier = -1 if err_suffix == 'err2' else 1
        return total_rel_err * df['planet_star_rad_ratio'] * multiplier

    df_eng['planet_star_rad_ratio_err1'] = propagate_ratio_err(df_eng, 'err1')
    df_eng['planet_star_rad_ratio_err2'] = propagate_ratio_err(df_eng, 'err2')

    # Insolation to Temperature (Log Energy Consistency)
    df_eng['log_energy_consistency'] = np.log10(df_eng['koi_insol']) - (4 * np.log10(df_eng['koi_teq']))
    df_eng['log_energy_consistency_err1'] = 0.434 * (df_eng['koi_insol_err1'] / df_eng['koi_insol']).abs()
    df_eng['log_energy_consistency_err2'] = 0.434 * (df_eng['koi_insol_err2'] / df_eng['koi_insol']).abs() * -1

    # Measurement Uncertainty Ratios
    targets = ['koi_period', 'koi_impact', 'koi_duration', 'koi_depth', 'koi_steff',
               'planet_star_rad_ratio', 'log_energy_consistency']
    epsilon = 1e-10
    for col in targets:
        error_range = df_eng[f'{col}_err1'] - df_eng[f'{col}_err2']
        df_eng[f'{col}_total_err_ratio'] = error_range / (df_eng[col] + epsilon)

    # Replace Posisble Infinities from the logs/divison w/ NaN & Drop
    df_eng = df_eng.replace([np.inf, -np.inf], np.nan).dropna()
    
    # Drop Original Error Columns
    err_cols = [c for c in df_eng.columns if '_err' in c and '_total_err_ratio' not in c]
    
    # Drop Features Used to Engineer Features
    base_features_to_drop = ['koi_prad', 'koi_teq', 'koi_insol', 'koi_slogg', 'koi_srad']
    
    # Combine Lists and Drop
    final_drop_list = err_cols + base_features_to_drop
    df_final = df_eng.drop(columns=final_drop_list, errors='ignore')

    return df_final

