# -*- coding: utf-8 -*-
"""FinalEDAnClean.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19cVhTK1fs2aQgiCUQ-Rxbq3yncyVvvUu
"""

import pandas as pd

def run_final_cleaning(df):
    kepler_final = df.copy()
    # Columns to Drop Based on Multicollinearity/VIF
    cols_to_drop = ['koi_impact','log_energy_consistency','koi_kepmag',
                    'log_energy_consistency_total_err_ratio']
    kepler_final = kepler_final.drop(columns=cols_to_drop, errors='ignore')
    return kepler_final

