# -*- coding: utf-8 -*-
"""KOIErrorAnalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Hz0W2BVnbNEcyvU6H0ajYibei9ypEsN

# Error Analysis

###Cosine Similarity to Robovetter Error, KMeans to Cluster the RF Errors, TSNE to Visualize Clusters
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.manifold import TSNE
import shap

def koi_error_analysis(pipeline, X_test, y_test, robo_error_id='K00242.01', n_clusters=3):
    # Get Incorrect Predictions from RF
    X_transformed = pipeline.named_steps['preprocessor'].transform(X_test)
    X_transformed = pipeline.named_steps['scaler'].transform(X_transformed)
    y_pred = pipeline.predict(X_test)
    error_mask = y_pred != y_test
    X_errors = X_transformed[error_mask]
    error_indices = X_test.index[error_mask]
    if len(X_errors) == 0:
        print("No errors found to analyze!")
        return

    # SHAP Waterfall for Matching Robovetter & RF Error 
    if robo_error_id in X_test.index:
        # 1. Isolate the specific observation and convert to DataFrame for feature names
        robo_loc = np.where(X_test.index == robo_error_id)[0][0]
        X_robo_transformed = X_transformed[robo_loc].reshape(1, -1)
        # Assuming the preprocessor step provides the feature names
        feature_names = pipeline.named_steps['preprocessor'].get_feature_names_out()
        X_robo_df = pd.DataFrame(X_robo_transformed, columns=feature_names)

        # 2. Generate SHAP values
        model = pipeline.named_steps['rf']
        explainer = shap.TreeExplainer(model)
        shap_values = explainer(X_robo_df)

        # 3. Plot (Index 1 usually represents the 'Candidate' class)
        plt.figure(figsize=(10, 6))
        plt.title(f"SHAP Waterfall for {robo_error_id}")
        shap.plots.waterfall(shap_values[0, :, 1])
        plt.show()
        
    # Similarity Check (>= 0.75)
    if robo_error_id in X_test.index:
        robo_idx = np.where(X_test.index == robo_error_id)[0][0]
        robo_vector = X_transformed[robo_idx].reshape(1, -1)
        similarities = cosine_similarity(X_errors, robo_vector).flatten()
        high_sim_mask = similarities >= 0.75
        high_sim_values = similarities[high_sim_mask]
        high_sim_indices = error_indices[high_sim_mask]
        print(f"High Similarity Errors to {robo_error_id} (>= 0.75)")
        if len(high_sim_values) > 0:
            for idx, sim in zip(high_sim_indices, high_sim_values):
                print(f"ID: {idx} | Similarity: {sim:.4f}")
        else:
            print("No errors met the 0.75 similarity threshold.")
        print(f"Average Similarity of all errors: {np.mean(similarities):.4f}\n")

    # KMeans Clustering on RF Errors
    kmeans = KMeans(n_clusters=n_clusters, random_state=42, n_init=10)
    clusters = kmeans.fit_predict(X_errors)
    sil_score = silhouette_score(X_errors, clusters)
    print(f"Silhouette Score: {sil_score:.4f}")

    # 4. TSNE to Visualize the Clusters 
    tsne = TSNE(n_components=2, perplexity=min(30, len(X_errors)-1), random_state=42)
    X_embedded = tsne.fit_transform(X_errors)
    plt.figure(figsize=(10, 7))
    my_palette = sns.color_palette('bright', 6)
    sns.scatterplot(x=X_embedded[:, 0], y=X_embedded[:, 1], hue=clusters, 
                    palette=my_palette, s=120, alpha=0.8, edgecolor='b')
    plt.title(f"TSNE Clusters of Model Errors)", fontsize=14)
    plt.xlabel("TSNE Component 1", fontsize=11)
    plt.ylabel("TSNE Component 2", fontsize=11)
    plt.legend(title="Cluster", bbox_to_anchor=(1.05, 1), loc='upper left')
    sns.despine()
    plt.show()
    return pd.DataFrame({'Cluster': clusters, 'Similarity_to_Robovetter': similarities}, index=error_indices)

