# -*- coding: utf-8 -*-
"""KOIErrorAnalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Hz0W2BVnbNEcyvU6H0ajYibei9ypEsN

# Error Analysis

###Cosine Similarity to Robovetter Error, KMeans to Cluster the RF Errors, TSNE to Visualize Clusters
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.manifold import TSNE

def koi_error_analysis(pipeline, X_test, y_test, robo_error_id='K00242.01', n_clusters=6):
    # Get Incorrect Predictions from RF
    X_transformed = pipeline.named_steps['preprocessor'].transform(X_test)
    X_transformed = pipeline.named_steps['scaler'].transform(X_transformed)
    y_pred = pipeline.predict(X_test)
    error_mask = y_pred != y_test
    X_errors = X_transformed[error_mask]
    error_indices = X_test.index[error_mask]
    if len(X_errors) == 0:
        print("No errors found to analyze!")
        return

    # Similarity Check (>= 0.75)
    if robo_error_id in X_test.index:
        robo_idx = np.where(X_test.index == robo_error_id)[0][0]
        robo_vector = X_transformed[robo_idx].reshape(1, -1)
        similarities = cosine_similarity(X_errors, robo_vector).flatten()
        high_sim_mask = similarities >= 0.75
        high_sim_values = similarities[high_sim_mask]
        high_sim_indices = error_indices[high_sim_mask]
        print(f"High Similarity Errors to {robo_error_id} (>= 0.75)")
        if len(high_sim_values) > 0:
            for idx, sim in zip(high_sim_indices, high_sim_values):
                print(f"ID: {idx} | Similarity: {sim:.4f}")
        else:
            print("No errors met the 0.75 similarity threshold.")
        print(f"Average Similarity of all errors: {np.mean(similarities):.4f}\n")

    # KMeans Clustering on RF Errors
    kmeans = KMeans(n_clusters=n_clusters, random_state=42, n_init=10)
    clusters = kmeans.fit_predict(X_errors)
    sil_score = silhouette_score(X_errors, clusters)
    print(f"Silhouette Score: {sil_score:.4f}")

    # 4. TSNE to Visualize the Clusters
    tsne = TSNE(n_components=2, perplexity=min(30, len(X_errors)-1), random_state=42)
    X_embedded = tsne.fit_transform(X_errors)
    plt.figure(figsize=(10, 7))
    sns.scatterplot(x=X_embedded[:, 0], y=X_embedded[:, 1],
                    hue=clusters, palette='viridis', s=100, style=clusters)
    plt.title(f"TSNE RF Errors")
    plt.legend(title="Cluster", bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.show()

    return pd.DataFrame({'Cluster': clusters, 'Similarity_to_Robovetter': similarities}, index=error_indices)

