# -*- coding: utf-8 -*-
"""KOIMain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bxcHeIWoZGZL6ZO3Cm3X5f3L_HpqtG0r

# Kepler Object Identification
# ML Main Execution
"""

import os
import sys

# 1. Clone your GitHub repository
repo_url = "https://github.com/sakobos/UNCCMSDSBA.git"
repo_name = "UNCCMSDSBA"

if not os.path.exists(repo_name):
    !git clone {repo_url}
else:
    # If it exists, pull latest changes in case you updated datainc.py
    !cd {repo_name} && git pull

# 2. Add the folder to the Python path so it can 'see' datainc.py
sys.path.append(f"/content/{repo_name}")

import datainc
import featureengineering
import finaledanclean
import datasplitter
import mpntrain
import modelevalnexp
import roboeval
import koierroranalysis
import importlib

"""###Data Ingestion & Cleaning"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# importlib.reload(datainc)
# datainc.ingest_and_clean_data()
# 
# # Separating kepler_clean and robovetter_df from the function-produced tuple
# kepler_clean, robovetter_df = datainc.ingest_and_clean_data()

"""###Feature Engineering"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# importlib.reload(featureengineering)
# koi_engineered = featureengineering.run_feature_pipeline(kepler_clean)

"""###Final Data Cleaning (Multicollinearity)"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# importlib.reload(finaledanclean)
# koi_ready, koi_blind = finaledanclean.run_final_cleaning(koi_engineered)

"""###Train Test Split"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# importlib.reload(datasplitter)
# X_train_pre, X_test_pre, y_train, y_test = datasplitter.splitter(koi_ready)

"""###Model Pipeline"""

importlib.reload(mpntrain)
kepler_model = mpntrain.kepler_pipeline(X_train_pre, y_train)

"""###Model Evaluation & Explanation"""

importlib.reload(modelevalnexp)
modelevalnexp.rf_eval(kepler_model, X_test_pre, y_test, threshold=0.75)
modelevalnexp.shap_exp(kepler_model, X_test_pre)

"""###Robovetter Evaluation"""

importlib.reload(roboeval)
roboeval.robovetter_errors(kepler_model, X_test_pre,
                                           robovetter_df, threshold=0.75)

"""###Model Error Analysis"""

importlib.reload(koierroranalysis)
koi_errors = koierroranalysis.koi_error_analysis(kepler_model, X_test_pre,
                                                 y_test, robo_error_id='K00242.01')