# -*- coding: utf-8 -*-
"""ModelEvalnExp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wENJSd6PUZLw4uKAGnmGmZSHTe8HTJ43

# Model Evaluation & Explainability
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import shap
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

def rf_eval(pipeline, X_test, y_test, threshold=0.75):
    test_probs = pipeline.predict_proba(X_test)[:, 1]
    y_pred = (test_probs >= threshold).astype(int)
    cm = confusion_matrix(y_test, y_pred)
    tn, fp, fn, tp = cm.ravel()
    fpr = fp / (fp + tn)
    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    print(f"Final Evaluation (Threshold: {threshold})")
    print(f"Accuracy:  {acc:7.2%}")
    print(f"Precision: {prec:7.2%}")
    print(f"Recall:    {rec:7.2%}")
    print(f"F1 Score:  {f1:7.2%}")
    print(f"FPR:       {fpr:7.2%}")
    plt.figure(figsize=(5, 4))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Purples', cbar=False)
    plt.title(f"RF Confusion Matrix\n(Threshold: {threshold})")
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.show()

def shap_exp(pipeline, X_test):
    model = pipeline.named_steps['rf']
    feature_names = X_test.columns.tolist()
    X_test_transformed = pipeline.named_steps['preprocessor'].transform(X_test)
    X_test_transformed = pipeline.named_steps['scaler'].transform(X_test_transformed)
    X_df = pd.DataFrame(X_test_transformed, columns=feature_names)
    explainer = shap.TreeExplainer(model)
    shap_values = explainer.shap_values(X_df)
    plt.figure(figsize=(10, 6))
    shap.summary_plot(shap_values[1], X_df, plot_type="dot")

