# -*- coding: utf-8 -*-
"""MPnTrain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12_g7QJpUyI8yac2YWaYTZ0QMkEAEy2Iv

# Model Pipeline & Training
"""

import pandas as pd
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PowerTransformer, StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RepeatedStratifiedKFold, cross_validate
from sklearn.metrics import accuracy_score, precision_score, recall_score

def kepler_pipeline(X_train, y_train):
    # High Skew Columns for the Yeo-Johnson Transform
    high_skew_cols = ['koi_period_total_err_ratio', 'koi_depth_total_err_ratio',
        'planet_star_rad_ratio', 'koi_impact_total_err_ratio',
        'koi_duration_total_err_ratio', 'koi_tce_plnt_num']

    # Create the YJ Transform portion of the Pipeline
    preprocessor = ColumnTransformer(transformers=[('yj',
                   PowerTransformer(method='yeo-johnson'), high_skew_cols)],
                                     remainder='passthrough')

    # Pipeline w/ YJ Transform, Stsandard Scaler, & Best RF Parameters
    pipeline = Pipeline(steps=[('preprocessor', preprocessor),
                              ('scaler', StandardScaler()),
                              ('rf', RandomForestClassifier(max_depth=10,
                               min_samples_leaf=2, n_estimators=200,
                               random_state=42, n_jobs=-1))])
    
    print("Repeated Stratified K-Fold Cross Validation:")
    rskf = RepeatedStratifiedKFold(n_splits=10, n_repeats=5, random_state=42)
    scoring_metrics = ['accuracy', 'precision', 'recall']
    
    cv_results = cross_validate(pipeline, X_train, y_train, cv=rskf, scoring=scoring_metrics, n_jobs=-1)
    
    print(f"CV Mean Accuracy:  {np.mean(cv_results['test_accuracy']):7.2%}")
    print(f"CV Mean Precision: {np.mean(cv_results['test_precision']):7.2%}")
    print(f"CV Mean Recall:    {np.mean(cv_results['test_recall']):7.2%}")
    print(f"CV Std Dev: {np.std(cv_results):.4f}")

    # 4. Final Training Fit
    pipeline.fit(X_train, y_train)
    y_train_pred = pipeline.predict(X_train)
    train_acc = accuracy_score(y_train, y_train_pred)
    train_prec = precision_score(y_train, y_train_pred)
    train_rec = recall_score(y_train, y_train_pred)

    print("Final Training Set Performance:")
    print(f"Training Accuracy:    {train_acc:7.2%}")
    print(f"Training Precision:   {train_prec:7.2%}")
    print(f"Training Recall:      {train_rec:7.2%}")
    return pipeline

