# -*- coding: utf-8 -*-
"""MPnTrain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12_g7QJpUyI8yac2YWaYTZ0QMkEAEy2Iv

# Model Pipeline & Training
"""

import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PowerTransformer, StandardScaler
from sklearn.ensemble import RandomForestClassifier

def kepler_pipeline(X_train, y_train):
    # High Skew Columns for the Yeo-Johnson Transform
    high_skew_cols = ['koi_period_total_err_ratio', 'koi_depth_total_err_ratio',
        'planet_star_rad_ratio', 'koi_impact_total_err_ratio',
        'koi_duration_total_err_ratio', 'koi_tce_plnt_num']

    # Create the YJ Transform portion of the Pipeline
    preprocessor = ColumnTransformer(transformers=[('yj',
                   PowerTransformer(method='yeo-johnson'), high_skew_cols)],
                                     remainder='passthrough')

    # Pipeline w/ YJ Transform, Stsandard Scaler, & Best RF Parameters
    pipeline = Pipeline(steps=[('preprocessor', preprocessor),
                              ('scaler', StandardScaler()),
                              ('rf', RandomForestClassifier(max_depth=None,
                               min_samples_leaf=2, n_estimators=200,
                               random_state=42, n_jobs=-1))])
    pipeline.fit(X_train, y_train)
    return pipeline

