# -*- coding: utf-8 -*-
"""RoboEval.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QfV4wUXZloh1moNkJ0hbMnRVFnD5NNBK

# Robovetter Evaluation & Edge Case Testing
"""

import pandas as pd

def robovetter_errors(pipeline, X_test, robovetter_df, threshold=0.75):
    # Identify Robovetter Errors
    robo_errors = robovetter_df[
        (robovetter_df['koi_pdisposition'] == 'CANDIDATE') &
        (robovetter_df['koi_disposition'] == 'FALSE POSITIVE')]

    error_ids = robo_errors.index.tolist()

    # Get the Robovetter Error Observations from the RF
    ids_to_check = [idx for idx in error_ids if idx in X_test.index]
    if not ids_to_check:
        print("No Robovetter errors found in the current Test Set.")
        return None
    X_error_cases = X_test.loc[ids_to_check]

    # Get the RF Predictions
    probs = pipeline.predict_proba(X_error_cases)[:, 1]
    preds = (probs >= threshold).astype(int)
    results = pd.DataFrame({'RF_Probability': probs,'RF_Prediction': preds,
                                'Actual_Label': 0}, index=ids_to_check)
    results['RF_Decision'] = results['RF_Prediction'].map({1: 'CONFIRMED', 0: 'FALSE POSITIVE'})
    print(f"Robovetter Error Analysis: ({len(ids_to_check)} cases)")
    for idx, row in results.iterrows():
        status = "RF Correctly Identified Robovetter Error" if row['RF_Prediction'] == 0 else "RF also Misclassfiied Robovetter Error"
        print(f"ID: {idx} | Prob: {row['RF_Probability']:.4f} | Result: {row['RF_Decision']} | {status}")
    return results

