# -*- coding: utf-8 -*-
"""SK KOI - Sandbox.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12K-jGbsGfmldeRqJVX2JJqqCCyiQppCG
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.preprocessing import PowerTransformer
from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, recall_score, classification_report, confusion_matrix, ConfusionMatrixDisplay, f1_score, precision_score, precision_recall_curve
from google.colab import drive
from google.colab import data_table
from IPython.core.interactiveshell import InteractiveShell
import math
from sklearn.calibration import CalibratedClassifierCV
from sklearn import set_config
import shap
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from sklearn.metrics import silhouette_score

# Getting rid of the sklearn HTML output box
set_config(display='text')
# Overwriting the default behavior to only display the last return of a cell
InteractiveShell.ast_node_interactivity = "all"

# Package Versions
import sys
import sklearn
import matplotlib
import xgboost
import statsmodels
print(f"{'Python':<20} | {sys.version.split()[0]}")
print(f"{'Scikit-Learn':<20} | {sklearn.__version__}")
print(f"{'SHAP':<20} | {shap.__version__}")
print(f"{'NumPy':<20} | {np.__version__}")
print(f"{'Pandas':<20} | {pd.__version__}")
print(f"{'Matplotlib':<20} | {matplotlib.__version__}")
print(f"{'Seaborn':<20} | {sns.__version__}")
print(f"{'XGBoost':<20} | {xgboost.__version__}")
print(f"{'Statsmodels':<20} | {statsmodels.__version__}")

# Importing Dataset
# Ensuring the dataset is available w/o access to My Drive
file_id = '1W6vu5CMyIrz4RdoSCJq_OpzCZwOJ79Hv'
url = f'https://drive.google.com/uc?id={file_id}'
kepler_df = pd.read_csv(url)
robovetter_df = kepler_df.copy()

"""# Feature Description:
#####**NASA Kepler Objects of Interest (KOI) Field Descriptions**

**Identification & Status**

kepid: Target identification number from the Kepler Input Catalog.

kepoi_name: Name used to identify the Kepler Object of Interest (e.g., K00001.01).

kepler_name: Official Kepler name assigned to confirmed planets.

koi_disposition: Current Archive disposition (Confirmed, False Positive, or Candidate).

koi_pdisposition: Suggested disposition based solely on Kepler data.

koi_score: A confidence value (0 to 1) for the disposition.

**Vetting Flags**

koi_fpflag_nt: Not Transit-Like False Positive Flag.

koi_fpflag_ss: Stellar Eclipse False Positive Flag.

koi_fpflag_co: Centroid Offset False Positive Flag.

koi_fpflag_ec: Ephemeris Match Indicates Contamination Flag.

**Orbital & Transit Parameters**

koi_period: Orbital Period [days].

koi_period_err1 / koi_period_err2: Period uncertainty (Upper/Lower).

koi_time0bk: Transit Epoch [BKJD] (Time of first observed transit).

koi_time0bk_err1 / koi_time0bk_err2: Epoch uncertainty (Upper/Lower).

koi_impact: Impact Parameter (Distance of path from star center).

koi_impact_err1 / koi_impact_err2: Impact uncertainty (Upper/Lower).

koi_duration: Transit Duration [hours].

koi_duration_err1 / koi_duration_err2: Duration uncertainty (Upper/Lower).

koi_depth: Transit Depth [parts per million].

koi_depth_err1 / koi_depth_err2: Depth uncertainty (Upper/Lower).

**Planetary Properties**

koi_prad: Planetary Radius [Earth radii].

koi_prad_err1 / koi_prad_err2: Radius uncertainty (Upper/Lower).

koi_teq: Equilibrium Temperature [Kelvin].

koi_teq_err1 / koi_teq_err2: Temp uncertainty (Upper/Lower). (Note: NASA only provides errors for specific models, often these are NaN).

koi_insol: Insolation Flux [Earth flux].

koi_insol_err1 / koi_insol_err2: Insolation uncertainty (Upper/Lower).

**Detection Metadata**

koi_model_snr: Transit Signal-to-Noise Ratio.

koi_tce_plnt_num: TCE Planet Number (Number of candidates found for this star).

koi_tce_delivname: TCE Delivery (The data processing pipeline version).

**Stellar Parameters**

koi_steff: Stellar Effective Temperature [Kelvin].

koi_steff_err1 / koi_steff_err2: Temp uncertainty (Upper/Lower).

koi_slogg: Stellar Surface Gravity [log10(cm/s²)].

koi_slogg_err1 / koi_slogg_err2: Gravity uncertainty (Upper/Lower).

koi_srad: Stellar Radius [Solar radii].

koi_srad_err1 / koi_srad_err2: Radius uncertainty (Upper/Lower).

**Positional & Brightness Data**

ra: Right Ascension (Sky coordinate).

dec: Declination (Sky coordinate).

koi_kepmag: Kepler-band Magnitude (Brightness of host star).

# EDA
"""

# Fist looks at the df
kepler_df.info()

kepler_df.head(10).T

# assert kepoi_name is unique
# kep_id is for the host star, which can have multiple candidate planets
assert kepler_df['kepoi_name'].is_unique

# setting index of kepoi_name
kepler_df.set_index('kepoi_name', inplace=True)

# taking a look the value counts for our categorical columns
for col in kepler_df.select_dtypes(include=['object', 'category']):
    print(kepler_df[col].value_counts(), "\n")

"""### Columnns to drop, descriptions, & explanations:

##### **koi_score** -> value calculated by NASAs Robovetter, a probability score of whether or not the candidate is a planet.
##### **koi_pdisposition** -> the suggested answer by the Robovetter, nearly mimics the koi_disposition (target) columm it's a data leak.
##### **koi_fpflag_nt, koi_fpflag_ss, koi_fpflag_co, & koi_fpflag_ec** -> these are derived from the heuristic set used by the Robovetter, would be "cheating" with the very thing we are trying to beat.
##### **koi_time0bk** Transit epoch is just a time stamp of the first observed transit. Not a feature of the star, but used for the creation of the orbital period (epoch 2 - epoch 1), which we have in our dataset.
##### **kepler_name** -> only named if it is a confirmed planet, data leak.
##### **kep_id** -> the ID of the star "hosting" the objects of interest, no predictive power as more of an "administrative" tag
##### **kepoi_name** -> Candidate ID, no predictive power. **Set as Index**
##### **koi_tce_delivname** -> version name of the software pipeline, no predictive power
##### **koi_tce_pint_num** -> count which number of candidate the object of interest is for the host star, no predictive power
##### **koi_insol** -> Insolation Flux is the measure of solar radiation on any given horizontal surface area. We already have koi_teq (temperature in Kelvin), which would be redundant to keep both, so keeping temperature as it is more intuitive.
##### **ra** & **dec** -> Right Ascension and Declination, sky coordinates. I don't believe planets are relgated to only certain pockets in the sky, so these will have no predictive power.
"""

# instead of dropping columns, will just select the columns I wish to retain
base_features = ['koi_disposition', 'koi_period', 'koi_impact', 'koi_duration',
                 'koi_depth', 'koi_prad', 'koi_teq', 'koi_insol', 'koi_model_snr',
                 'koi_tce_plnt_num', 'koi_steff', 'koi_slogg', 'koi_srad', 'koi_kepmag']
pattern = '^' + '|^'.join(base_features)
kepler_trim = kepler_df.filter(regex=pattern)

# checking new form
kepler_trim.info()

# Dropping koi_teqq_err1 & koi_teq_err2 since they are fully null
kepler_trim = kepler_trim.drop(columns=['koi_teq_err1', 'koi_teq_err2'])

# Dropping NULLs
kepler_clean = kepler_trim.dropna().copy()

kepler_clean.info()

kepler_clean['koi_disposition'].value_counts()

# Summary statistics
kepler_clean.describe().T

# Checking for Multicollinearity
# same as base_features, just removing koi_disposition
base_cols = ['koi_period', 'koi_impact', 'koi_duration', 'koi_depth',
             'koi_prad', 'koi_teq', 'koi_insol', 'koi_model_snr',
             'koi_steff', 'koi_slogg', 'koi_srad', 'koi_kepmag']
corr_matrix = kepler_clean[base_cols].corr()
plt.figure(figsize=(12, 8))
sns.heatmap(corr_matrix, annot=True, cmap='Purples', fmt=".2f")
plt.title("Base Feature Multicollinearity")
plt.show();

# Double checking with VIF
vif_data = pd.DataFrame()
vif_data["feature"] = base_cols
vif_data["VIF"] = [variance_inflation_factor(kepler_clean[base_cols].values, i) for i in range(len(base_cols))]
print(vif_data.sort_values(by="VIF", ascending=False))

# Some problematic multicollinearity concerns, but will be using some of those features to
# engineer new features, so they will be dropped after

kepler_clean.info()

"""##### Will need to further trim the dataframe, not by features, but by observation, as we want either Confirmed exoplanets or verified False Positives. The Candidate observations can be used as the first example of a 'production batch' where we can offer classifications and prediction probabilites for the initial phase of manual verification/validation prior to full automation of the classifier solution.

# Feature Engineering
"""

# Planet to Star Size Ratio
# an exoplanet is much smaller than a star, so if the ratio of object of
# interest is too high, then it is most likely not an exoplanet
# koi_prad is in Earth radii
# koi_srad is in Solar radii
# must convert
SOLAR_TO_EARTH_RADIUS = 109.076
kepler_clean['planet_star_rad_ratio'] = kepler_clean['koi_prad'] / (kepler_clean['koi_srad'] * SOLAR_TO_EARTH_RADIUS)
print(kepler_clean['planet_star_rad_ratio'].describe())

# New error for upper (err1) and lower (err2) bounds to account for the measurement
# error that propogates into the size ratio calculation
def propagate_ratio_err(df, err_suffix):
    # Relative Errors (err / measurement)
    rel_err_prad = (df[f'koi_prad_{err_suffix}'] / df['koi_prad']).abs()
    rel_err_srad = (df[f'koi_srad_{err_suffix}'] / df['koi_srad']).abs()
    total_rel_err = np.sqrt(rel_err_prad**2 + rel_err_srad**2)
    multiplier = -1 if err_suffix == 'err2' else 1
    return total_rel_err * df['planet_star_rad_ratio'] * multiplier
kepler_clean['planet_star_rad_ratio_err1'] = propagate_ratio_err(kepler_clean, 'err1')
kepler_clean['planet_star_rad_ratio_err2'] = propagate_ratio_err(kepler_clean, 'err2')
kepler_clean[['planet_star_rad_ratio', 'planet_star_rad_ratio_err1', 'planet_star_rad_ratio_err2']].head(10)

# New feature for the proportionality of Insolation to Temperature
# The power a planet radiates (temperature^4) should be proportional
# to the energy it receives from its star (insolation)
# if a planet has a proportion of ionsolation to power that is too
# small, it is likely the object is s star, not an exoplanet
kepler_clean['energy_consistency'] = kepler_clean['koi_insol'] / (kepler_clean['koi_teq']**4)

# New error for propagation through new feature calc
# we do not have koi_teqq errors, so the error is just based off the
# insolation error bounds
def propagate_energy_err(df, err_suffix):
    rel_err_insol = (df[f'koi_insol_{err_suffix}'] / df['koi_insol']).abs()
    multiplier = -1 if err_suffix == 'err2' else 1
    return rel_err_insol * df['energy_consistency'] * multiplier

kepler_clean['energy_consistency_err1'] = propagate_energy_err(kepler_clean, 'err1')
kepler_clean['energy_consistency_err2'] = propagate_energy_err(kepler_clean, 'err2')
kepler_clean[['energy_consistency', 'energy_consistency_err1', 'energy_consistency_err2', 'koi_disposition']].head(10)

# energy_consistency is on a super small scale, checking log and on errors as well
kepler_clean['log_energy_consistency'] = np.log10(kepler_clean['koi_insol']) - (4 * np.log10(kepler_clean['koi_teq']))
kepler_clean['log_energy_consistency_err1'] = 0.434 * (kepler_clean['koi_insol_err1'] / kepler_clean['koi_insol']).abs()
kepler_clean['log_energy_consistency_err2'] = 0.434 * (kepler_clean['koi_insol_err2'] / kepler_clean['koi_insol']).abs() * -1
kepler_clean[['log_energy_consistency', 'log_energy_consistency_err1', 'log_energy_consistency_err2']].head(10)

# Measurement Uncertainty Ratios for features that will remain after trimming
targets = ['koi_period', 'koi_impact', 'koi_duration', 'koi_depth', 'koi_steff',
           'planet_star_rad_ratio', 'log_energy_consistency']
# adding in a tiny epsilon to prevent divison by 0 error
epsilon = 1e-10
for col in targets:
    error_range = kepler_clean[f'{col}_err1'] - kepler_clean[f'{col}_err2']
    kepler_clean[f'{col}_total_err_ratio'] = error_range / (kepler_clean[col] + epsilon)
kepler_clean[[f'{col}_total_err_ratio' for col in targets]].head()

kepler_clean.info()

"""# Additional EDA for Final DF"""

# Viewing dataframe before trimming
kepler_clean.info()

# Trimming dataset for final desired features
final_columns = ['koi_disposition', 'koi_period', 'koi_impact', 'koi_duration',
                 'koi_depth', 'koi_model_snr', 'koi_tce_plnt_num', 'koi_steff',
                 'koi_kepmag', 'planet_star_rad_ratio', 'log_energy_consistency',
                 'koi_period_total_err_ratio', 'koi_impact_total_err_ratio',
                 'koi_duration_total_err_ratio', 'koi_depth_total_err_ratio',
                 'koi_steff_total_err_ratio', 'planet_star_rad_ratio_total_err_ratio',
                 'log_energy_consistency_total_err_ratio']
kepler_final = kepler_clean[final_columns].copy()
kepler_final.info()

kepler_final.describe().T

# Checking for Multicollinearity
# same as base_features, just removing koi_disposition
features_only = [col for col in kepler_final.columns if col != 'koi_disposition']
corr_matrix = kepler_final[features_only].corr()
plt.figure(figsize=(16, 10))
sns.heatmap(corr_matrix, annot=True, cmap='Purples', fmt=".2f", cbar_kws={'label': 'Correlation Coefficient'})
plt.title("Final Kepler DF Multicollinearity", fontsize=15)
plt.xticks(rotation=45, ha='right')
plt.show();

# Double checking with VIF
vif_data = pd.DataFrame()
vif_data["feature"] = features_only
vif_data["VIF"] = [variance_inflation_factor(kepler_final[features_only].values, i) for i in range(len(features_only))]
print(vif_data.sort_values(by="VIF", ascending=False))

# Drop koi_impact, highly collinear with planet_star_rad_ratio
# Also need to drop log_energy_consistency, as it has very little variance
# which is blowing up the VIF
kepler_final.drop(columns=['koi_impact', 'log_energy_consistency'], inplace=True)

# Checking for Multicollinearity again
# same as base_features, just removing koi_disposition
features_only = [col for col in kepler_final.columns if col != 'koi_disposition']
corr_matrix = kepler_final[features_only].corr()
plt.figure(figsize=(16, 10))
sns.heatmap(corr_matrix, annot=True, cmap='Purples', fmt=".2f", cbar_kws={'label': 'Correlation Coefficient'})
plt.title("Final Kepler DF Multicollinearity", fontsize=15)
plt.xticks(rotation=45, ha='right')
plt.show();

# Double checking with VIF again
vif_data = pd.DataFrame()
vif_data["feature"] = features_only
vif_data["VIF"] = [variance_inflation_factor(kepler_final[features_only].values, i) for i in range(len(features_only))]
print(vif_data.sort_values(by="VIF", ascending=False))

# Star temperature and brightness are highly correlated
# some of the error measurements are correlated as well
# the telescope "having a bad day" essentially
kepler_final = kepler_final.drop(columns=['koi_kepmag', 'log_energy_consistency_total_err_ratio']).copy()

# right into VIF
features_only = [col for col in kepler_final.columns if col != 'koi_disposition']
vif_data = pd.DataFrame()
vif_data["feature"] = features_only
vif_data["VIF"] = [variance_inflation_factor(kepler_final[features_only].values, i) for i in range(len(features_only))]
print(vif_data.sort_values(by="VIF", ascending=False))

kepler_final.info()

# koi_steff is related to its error, since hotter stars are more difficult to measure
# although VIF > 10, its still under 20, which should not impact the model too severely

# Checking for skew
# 2. Numerical Skewness Check
# Skew > 1.0 = Highly Skewed (Positive/Right)
# Skew < -1.0 = Highly Skewed (Negative/Left)
skew_vals = kepler_final[features_only].skew().sort_values(ascending=False)
print("Numeric Skewness:")
print(skew_vals)

num_features = len(features_only)
cols = 3
rows = math.ceil(num_features / cols)
plt.figure(figsize=(15, rows * 4))
for i, col in enumerate(features_only):
    plt.subplot(rows, cols, i + 1)
    sns.histplot(kepler_final[col], kde=True, color='purple', bins=30)
    current_skew = kepler_final[col].skew()
    plt.title(f"{col}\nSkew: {current_skew:.2f}", fontsize=10)
    plt.xlabel("")
    plt.ylabel("")
plt.tight_layout()
plt.show();

# Log Transforming every feature except koi_steff
cols_to_log = ['koi_period', 'koi_duration', 'koi_depth', 'koi_model_snr',
               'koi_tce_plnt_num', 'planet_star_rad_ratio',
               'koi_period_total_err_ratio', 'koi_impact_total_err_ratio',
               'koi_duration_total_err_ratio', 'koi_depth_total_err_ratio',
               'koi_steff_total_err_ratio', 'planet_star_rad_ratio_total_err_ratio']
kepler_transformed = kepler_final.copy()
for col in cols_to_log:
    kepler_transformed[col] = np.log1p(kepler_transformed[col])

kepler_transformed.info()

# Checking skew again
skew_vals2 = kepler_transformed[features_only].skew().sort_values(ascending=False)
print("Numeric Skewness:")
print(skew_vals2)

num_features = len(features_only)
cols = 3
rows = math.ceil(num_features / cols)
plt.figure(figsize=(15, rows * 4))
for i, col in enumerate(features_only):
    plt.subplot(rows, cols, i + 1)
    sns.histplot(kepler_transformed[col], kde=True, color='purple', bins=30)
    current_skew = kepler_transformed[col].skew()
    plt.title(f"{col}\nSkew: {current_skew:.2f}", fontsize=10)
    plt.xlabel("")
    plt.ylabel("")
plt.tight_layout()
plt.show();

# Trying Yeo-Johnson Power Transform to address the remaining heavily skewed features
pt = PowerTransformer(method='yeo-johnson')
high_skew_cols = ['koi_period_total_err_ratio', 'koi_depth_total_err_ratio',
                  'planet_star_rad_ratio', 'koi_impact_total_err_ratio',
                  'koi_duration_total_err_ratio', 'koi_tce_plnt_num']
kepler_transformed[high_skew_cols] = pt.fit_transform(kepler_transformed[high_skew_cols])

print(kepler_transformed[high_skew_cols].skew())

"""###realized YJ Transform will result in data leakage if ran on the entire dataset, need to push to the pipeline phase after train test spli"""

# Since Yeo-johnson was much more effective, I will skip the log transform and
# Y-J from the get-go
cols_to_log = ['koi_period', 'koi_duration', 'koi_depth', 'koi_model_snr',
               'koi_tce_plnt_num', 'planet_star_rad_ratio',
               'koi_period_total_err_ratio', 'koi_impact_total_err_ratio',
               'koi_duration_total_err_ratio', 'koi_depth_total_err_ratio',
               'koi_steff_total_err_ratio', 'planet_star_rad_ratio_total_err_ratio']
kepler_yjtf = kepler_final.copy()
pt = PowerTransformer(method='yeo-johnson')
kepler_yjtf[cols_to_log] = pt.fit_transform(kepler_yjtf[cols_to_log])
print(kepler_yjtf[cols_to_log].skew())

"""##### need to rename the features to add _yj to denote its transformation"""

# Final view of data frame kepler_yjtf
kepler_yjtf.info()

kepler_yjtf.describe().T

"""#####Going to usde kf_final, skipping over the transformed dataframe, due to the data leak.
#####Will train test split and YJ transform onthe train, then apply to the test

# Final Cleaning Step
#### koi_disposition has 3 categories, Confirmed, False Positive, and Candidate. I will remove all Candidate observations to leave as a 'first production run' for the final model to rank those candidates by prediction probability for manual validation.
"""

# Splitting out Candidate observations
koi_candidates = kepler_final[kepler_final['koi_disposition'] == 'CANDIDATE'].copy()
known_dispositions = ['CONFIRMED', 'FALSE POSITIVE']
koi_model_data = kepler_final[kepler_final['koi_disposition'].isin(known_dispositions)].copy()
print(f"Model Data (Training/Test): {koi_model_data.shape[0]} observations")
print(f"Candidate Data (Blind):    {koi_candidates.shape[0]} observations")
print(f"\n Class Balance in Model Data:\n{koi_model_data['koi_disposition'].value_counts()}")

# Encoding koi_disposition, False Positive = 0, Confirmed = 1
koi_model_data['koi_disposition'] = koi_model_data['koi_disposition'].map({
    'CONFIRMED': 1, 'FALSE POSITIVE': 0})
X = koi_model_data.drop(columns=['koi_disposition'])
y = koi_model_data['koi_disposition']
print(y.value_counts())
print(f"\nTarget Name: {y.name}")
print(f"Data Type:   {y.dtype}")

"""# Creating Model Pipelines
### -> splitting data 90/10 train/test
### -> creating pipelines for SVC, RF, XGBoost
### -> pipelines will scale data,  gridsearch for each fold evaluating on precision, run repeated stratified k fold cross validation to try to incite robustness even w/ low sample sizes, and run with class weights to address target imbalance.
"""

# Train Test Split & YJ Transform for Skew
X = koi_model_data.drop(columns=['koi_disposition'])
y = koi_model_data['koi_disposition']
X_train_pre, X_test_pre, y_train, y_test = train_test_split(
    X, y, test_size=0.10, random_state=42, stratify=y)
cols_to_log = ['koi_period', 'koi_duration', 'koi_depth', 'koi_model_snr',
               'koi_tce_plnt_num', 'planet_star_rad_ratio',
               'koi_period_total_err_ratio', 'koi_impact_total_err_ratio',
               'koi_duration_total_err_ratio', 'koi_depth_total_err_ratio',
               'koi_steff_total_err_ratio', 'planet_star_rad_ratio_total_err_ratio']
pt = PowerTransformer(method='yeo-johnson')

# YJ Transform on Training Set Only to Avoid The Data Leak
X_train_pre[cols_to_log] = pt.fit_transform(X_train_pre[cols_to_log])
# Applying to the Test
X_test_pre[cols_to_log] = pt.transform(X_test_pre[cols_to_log])
# Checking Skew
print("Training Set Skewness:")
print(X_train_pre[cols_to_log].skew())
print("\nTest Set Skewness:")
print(X_test_pre[cols_to_log].skew())

"""#####koi_tce_plnt_num is still just outside my ideal 1.5 threshold, but will allow it, as it is just barely"""

# Establishing Repeated Stratified K Fold Cross Validation
rskf = RepeatedStratifiedKFold(n_splits=10, n_repeats=5, random_state=42)

# Creating weights for XGBoost
neg_count = np.sum(y_train == 0)
pos_count = np.sum(y_train == 1)
weight_ratio = neg_count / pos_count

# Random Forest Pipeline and Hyperparameters
rf_pipe = Pipeline([('scaler', StandardScaler()),
 ('rf', RandomForestClassifier(random_state=42, class_weight='balanced'))])
rf_params = {'rf__n_estimators': [100, 200],'rf__max_depth': [5, 10, 15, 20],
             'rf__min_samples_leaf': [1, 2]}

# XGBoost Pipeline and Hyperparameters
xgb_pipe = Pipeline([('scaler', StandardScaler()),
                     ('xgb', XGBClassifier(random_state=42, eval_metric='logloss', scale_pos_weight=weight_ratio))])
xgb_params = {'xgb__n_estimators': [100, 200],'xgb__learning_rate': [0.01, 0.1],'xgb__max_depth': [3, 5]}

# SVC Pipeline and Hyperparameters
svc_pipe = Pipeline([('scaler', StandardScaler()),
 ('svc', SVC(probability=True, random_state=42, class_weight='balanced'))])
svc_params = {'svc__C': [0.1, 1, 10],'svc__kernel': ['rbf', 'poly'],
              'svc__gamma': ['scale', 'auto']}

# Running Grid Search
classifiers = {'Random Forest': (rf_pipe, rf_params),
               'XGBoost': (xgb_pipe, xgb_params),
               'SVC': (svc_pipe, svc_params)}
best_models = {}
for name, (pipe, params) in classifiers.items():
    print(f"Running Grid Search for {name}...")
    grid = GridSearchCV(pipe, params, cv=rskf, scoring='precision', n_jobs=-1)
    grid.fit(X_train_pre, y_train)
    best_models[name] = grid.best_estimator_
    print(f"Best Params for {name}: {grid.best_params_}\n")

# Model Eval and Confusion Matrices
# w/o Decision Threshold Tuning
fig, axes = plt.subplots(1, 3, figsize=(18, 5));
results_table = []
for i, (name, model) in enumerate(best_models.items()):
    y_pred = model.predict(X_test_pre)
    acc = round((accuracy_score(y_test, y_pred)) * 100, 2)
    prec = round((precision_score(y_test, y_pred)) * 100, 2)
    rec = round((recall_score(y_test, y_pred)) * 100, 2)
    f1 = round((f1_score(y_test, y_pred)) * 100, 2)
    cm = confusion_matrix(y_test, y_pred)
    tn, fp, fn, tp = cm.ravel()
    fpr = round((fp / (fp + tn)) * 100, 2)
    results_table.append({'Model': name, 'Accuracy': acc, 'Precision': prec,
                          'Recall': rec, 'F1': f1, 'FPR': fpr})
    sns.heatmap(cm, annot=True, fmt='d', cmap='Purples', ax=axes[i], cbar=False)
    axes[i].set_title(f"{name} Confusion Matrix");
    axes[i].set_xlabel("Predicted");
    axes[i].set_ylabel("Actual");
plt.tight_layout();
plt.show();

df_results = pd.DataFrame(results_table)
print("\nModel Rank:")
print(df_results.sort_values(by='Precision', ascending=False).to_string(index=False))

# Finding the best decision threshold
thresholds = np.arange(0.1, 1.0, 0.05)
threshold_results = []
best_model = best_models['Random Forest']
probs = best_model.predict_proba(X_test_pre)[:, 1]
for t in thresholds:
    y_pred_t = (probs >= t).astype(int)
    prec = precision_score(y_test, y_pred_t, zero_division=0)
    rec = recall_score(y_test, y_pred_t)
    cm = confusion_matrix(y_test, y_pred_t)
    tn, fp, fn, tp = cm.ravel()
    fpr = fp / (fp + tn) if (fp + tn) > 0 else 0
    threshold_results.append({'Threshold': t,'Precision': prec,'Recall': rec,
                              'FPR': fpr})
df_thresh = pd.DataFrame(threshold_results)
print(df_thresh.to_string(index=False))
plt.figure(figsize=(8, 5))
plt.plot(df_thresh['Threshold'], df_thresh['Precision'], label='Precision', marker='o')
plt.plot(df_thresh['Threshold'], df_thresh['Recall'], label='Recall', marker='x')
plt.title('Threshold vs. Precision & Recall (Random Forest)')
plt.xlabel('Decision Threshold')
plt.ylabel('Score')
plt.legend()
plt.grid(True)
plt.show();

# Best Random Forest w/ Decision Threshold
final_rf_pipe = best_models['Random Forest']
custom_threshold = 0.75
test_probs = final_rf_pipe.predict_proba(X_test_pre)[:, 1]
y_pred_custom = (test_probs >= custom_threshold).astype(int)
cm_custom = confusion_matrix(y_test, y_pred_custom)
tn, fp, fn, tp = cm_custom.ravel()
print(f"Final Evaluation: Random Forest @ {custom_threshold} Threshold")
print(classification_report(y_test, y_pred_custom))
print(f"Precision: {precision_score(y_test, y_pred_custom):.4f}")
print(f"False Positive Rate (FPR): {fp / (fp + tn):.4f}")
print(f"Recall: {recall_score(y_test, y_pred_custom):.4f}")
plt.figure(figsize=(6, 5))
sns.heatmap(cm_custom, annot=True, fmt='d', cmap='Purples', cbar=False)
plt.title(f"Random Forest Final Confusion Matrix\n(Threshold: {custom_threshold})")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

"""# Best Model
###** Random Forest **
##### Max Depth: None
##### Min Samples Leaf: 2
##### Estimators: 200

#### **Precision: 93.59%**
#### **FPR: 2.84%**
#### Recall: 80.51%
#### Accuracy: 90.20%
#### Decision Threshold of .75

# Model Explainability (SHAP)
"""

# From best RF Model
best_rf_pipe = best_models['Random Forest']
model = best_rf_pipe.named_steps['rf']
scaler = best_rf_pipe.named_steps['scaler']
X_test_transformed = scaler.transform(X_test_pre)
X_test_transformed_df = pd.DataFrame(X_test_transformed, columns=X.columns)
explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(X_test_transformed_df)
plt.figure(figsize=(12, 10))
shap.summary_plot(
    shap_values[:, :, 1],
    X_test_transformed_df,
    plot_type="dot",
    max_display=X_test_transformed_df.shape[1],
    show=False
)
plt.title("Random Forest Global Feature Importance (Confirmed Class)")
plt.tight_layout()
plt.show()

"""# Evaluating Robovetter"""

# Checking out Robovetter
robovetter_df['koi_pdisposition'].value_counts()
robovetter_df['koi_disposition'].value_counts()

robo_eval = robovetter_df[robovetter_df['koi_disposition'].isin(['CONFIRMED', 'FALSE POSITIVE'])].copy()
y_true_robo = robo_eval['koi_disposition'].map({'CONFIRMED': 1, 'FALSE POSITIVE': 0})
y_pred_robo = robo_eval['koi_pdisposition'].map({'CANDIDATE': 1, 'FALSE POSITIVE': 0})
robo_acc  = accuracy_score(y_true_robo, y_pred_robo)
robo_prec = precision_score(y_true_robo, y_pred_robo)
robo_rec  = recall_score(y_true_robo, y_pred_robo)
robo_f1   = f1_score(y_true_robo, y_pred_robo)
robovetter_candidates = robovetter_df[robovetter_df['koi_pdisposition'] == 'CANDIDATE'].copy()
candidate_outcomes = robovetter_candidates['koi_disposition'].value_counts()
fps = candidate_outcomes.get('FALSE POSITIVE', 0)
confirmed = candidate_outcomes.get('CONFIRMED', 0)
total_resolved = fps + confirmed
fpr_robovetter = (fps / total_resolved) * 100
print("Robovetter Performance:")
print(f"Accuracy:  {robo_acc:.4f}")
print(f"Precision: {robo_prec:.4f}")
print(f"Recall:    {robo_rec:.4f}")
print(f"F1 Score:  {robo_f1:.4f}")
print(f"FPR:       {fpr_robovetter:.4f}")

# Isolating the Observation the Robovetter got wrong
robovetter_error = robovetter_df[(robovetter_df['koi_pdisposition'] == 'CANDIDATE')
                        & (robovetter_df['koi_disposition'] == 'FALSE POSITIVE')]
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)
display(robovetter_error)

# Since this observastion was in the training set, the model learned off of it,
# not predicted it, so we will run it through the model to see what it predicts it to be
# Creating a new pipeline without this one observation, while using the same best
# parameters and decision threshold from our normal training.
# this will allow us to generate a prediction for our desired observation
# without it having been already seen by our model
target_name = 'K00242.01'
X_target_obs = X_train_pre.loc[[target_name]]
y_target_true = y_train.loc[target_name]
X_train_surgical = X_train_pre.drop(index=target_name)
y_train_surgical = y_train.drop(index=target_name)
best_params = best_models['Random Forest'].named_steps['rf'].get_params()
surgical_pipe = Pipeline([('scaler', StandardScaler()),
 ('rf', RandomForestClassifier(**best_params))])
surgical_pipe.fit(X_train_surgical, y_train_surgical)
blind_prob = surgical_pipe.predict_proba(X_target_obs)[0, 1]
custom_threshold = 0.75
final_decision = "CONFIRMED" if blind_prob >= custom_threshold else "FALSE POSITIVE"
print(f"Absolute Blind Case Study: {target_name} ---")
print(f"True Disposition:  {'CONFIRMED' if y_target_true == 1 else 'FALSE POSITIVE'}")
print(f"Model Probability: {blind_prob:.4f}")
print(f"Decision (@ {custom_threshold}): {final_decision}")
if (y_target_true == 0 and final_decision == "FALSE POSITIVE"):
    print(f"\nSUCCESS: The model correctly identified {target_name} as a False Positive!")

# ^^^ did ML get it right while RV got it wrong?
# No, ML Confirmed instead of labeling as FP
# SHAP to figure out why
model = surgical_pipe.named_steps['rf']
scaler = surgical_pipe.named_steps['scaler']
X_target_transformed = scaler.transform(X_target_obs)
X_target_df = pd.DataFrame(X_target_transformed, columns=X_target_obs.columns)
explainer = shap.TreeExplainer(model)
shap_values = explainer(X_target_df)
plt.figure(figsize=(10, 6))
shap.plots.waterfall(shap_values[0, :, 1])
plt.show();

"""# Model Error Analysis

#### How close were these incorrect classifications to the observation the Robovetter missed?
#### Can we group these observations together to see if ther are any patterns?
"""

# Making a kepler_errors dartaframe for the incorrect ML classifications
# untransformed, going off the raw observation data
kepler_errors = koi_model_data.copy()
pd.set_option('display.max_rows', None)
print(len(kepler_errors))

# Making kepler_errors the incorrect predictions only
missed_mask = (y_test != y_pred_custom)
missed_names = y_test[missed_mask].index.tolist()
kepler_errors_final = kepler_errors.loc[missed_names]
print(f"Total Test Observations: {len(y_test)}")
print(f"Number of Missed Predictions: {len(kepler_errors_final)}")
display(kepler_errors_final.head())

# Summary Statistics of Errors
kepler_errors_final.describe().T

# Redisplaying the lone Robovetter Error
observation_242 = kepler_errors.loc[['K00242.01']]
display(observation_242.T)

# Compute Cosine Similarity for each ML Error against Robovetter Error
# Dropping the known identical error by kepoi_name
target_name = 'K00242.01'
features_to_scale = ['koi_period', 'koi_duration', 'planet_star_rad_ratio',
                     'koi_depth','koi_model_snr', 'koi_tce_plnt_num',
                     'koi_steff','koi_period_total_err_ratio',
                     'koi_duration_total_err_ratio','koi_depth_total_err_ratio',
                     'koi_steff_total_err_ratio']
target_row_raw = observation_242.loc[[target_name], features_to_scale]
comparison_pool = pd.concat([kepler_errors_final[features_to_scale], target_row_raw])
scaler_sim = StandardScaler()
scaled_data = scaler_sim.fit_transform(comparison_pool)
X_scaled_pool = pd.DataFrame(scaled_data, index=comparison_pool.index, columns=features_to_scale)
target_vector_scaled = X_scaled_pool.loc[[target_name]]
sim_scores = cosine_similarity(X_scaled_pool, target_vector_scaled)
comparison_pool['scaled_cosine_sim'] = sim_scores
final_results = comparison_pool[comparison_pool.index != target_name]
print(f"Observations Most Similar to {target_name}")
display(final_results['scaled_cosine_sim'].sort_values(ascending=False))

# Only observations with a cosine similarity of > .75
top_similarity = final_results[final_results['scaled_cosine_sim'] > .75]
display(top_similarity)

# Distribution of scores
final_results['scaled_cosine_sim'].describe().T

# Cluster all ML Errors to see if we can find some patterns
# Elbow Plot first for optimal K
inertia = []
K_range = range(1, 11)

for k in K_range:
    km = KMeans(n_clusters=k, random_state=42, n_init=10)
    km.fit(X_scaled_pool)
    inertia.append(km.inertia_)
plt.figure(figsize=(8, 5))
plt.plot(K_range, inertia, marker='o', linestyle='--', color='b')
plt.xlabel('Number of Clusters (k)')
plt.ylabel('Inertia (Within-Cluster Sum of Squares)')
plt.title('Elbow Method to Find Optimal Clusters for Error Analysis')
plt.xticks(K_range)
plt.grid(True, linestyle=':', alpha=0.6)
plt.show()

# Small enough dataset that we can pick # of clusters by silhouette score
k_range = [3, 4, 5, 6, 7, 8, 9, 10]
scores = []
results = []
print("Silhouette Analysis & Cluster Distribution")
for k in k_range:
    km = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = km.fit_predict(X_scaled_pool)
    score = silhouette_score(X_scaled_pool, labels)
    scores.append(score)
    counts = pd.Series(labels).value_counts().sort_index().to_dict()
    print(f"k={k} | Silhouette Score: {score:.4f} | Cluster Sizes: {list(counts.values())}")
plt.figure(figsize=(8, 5))
plt.plot(k_range, scores, marker='s', color='darkorange', linewidth=2)
plt.title('Choosing Optimal k: Silhouette Score')
plt.xlabel('Number of Clusters (k)')
plt.ylabel('Silhouette Score (Higher is Better)')
plt.xticks(k_range)
plt.grid(True, linestyle=':', alpha=0.6)
plt.show()

# K Means w/ k=3 from the elbow plot & Silhouette Score Plot
# although w/ a peak S.S of .3890, these clusters are quite weak
scaler_temp = StandardScaler()
X_only_errors_scaled = scaler_temp.fit_transform(kepler_errors_final[features_to_scale])
n_clusters = 3
kmeans = KMeans(n_clusters=n_clusters, random_state=42, n_init=10)
clusters = kmeans.fit_predict(X_only_errors_scaled)
kepler_errors_final['cluster'] = clusters
cluster_summary = kepler_errors_final.groupby('cluster')[features_to_scale].mean()
display(cluster_summary)

pca = PCA(n_components=2)
components = pca.fit_transform(X_only_errors_scaled)
pca_df = pd.DataFrame(data=components, columns=['PC1', 'PC2'], index=kepler_errors_final.index)
pca_df['cluster'] = kepler_errors_final['cluster']
plt.figure(figsize=(10, 6))
sns.scatterplot(data=pca_df, x='PC1', y='PC2', hue='cluster', palette='tab10', s=100, alpha=0.8)
plt.title('Error Clusters: PCA Dimension Reduction')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.legend(title='Cluster', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(True, linestyle=':', alpha=0.6)
plt.show()
plt.figure(figsize=(10, 6))
sns.scatterplot(data=kepler_errors_final, x='koi_period', y='koi_model_snr',
                hue='cluster', palette='tab10', s=100)
plt.yscale('log')
plt.title('Physical Distribution: Orbital Period vs. Signal-to-Noise Ratio')
plt.xlabel('Orbital Period (Days)')
plt.ylabel('Signal-to-Noise Ratio (Log Scale)')
plt.legend(title='Cluster', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()
from sklearn.preprocessing import MinMaxScaler
scaler_heat = MinMaxScaler()
summary_scaled = pd.DataFrame(scaler_heat.fit_transform(cluster_summary),
                              index=cluster_summary.index,
                              columns=cluster_summary.columns)

plt.figure(figsize=(12, 6))
sns.heatmap(summary_scaled, annot=True, cmap='YlGnBu', fmt=".2f")
plt.title('Normalized Feature Fingerprints per Cluster (0=Min, 1=Max)')
plt.ylabel('Cluster ID')
plt.show();

# TSNE since PCA was decent but looks like Cluster 4
# could just be behind Cluster 3 in a higher dimension
tsne = TSNE(n_components=2, perplexity=10, random_state=42, init='pca', learning_rate='auto')
tsne_results = tsne.fit_transform(X_only_errors_scaled)
tsne_df = pd.DataFrame(data=tsne_results, columns=['tsne_1', 'tsne_2'], index=kepler_errors_final.index)
tsne_df['cluster'] = kepler_errors_final['cluster']
plt.figure(figsize=(10, 6))
sns.scatterplot(data=tsne_df, x='tsne_1', y='tsne_2', hue='cluster', palette='tab10', s=120, alpha=0.9, edgecolor='w')
plt.title('Error Clusters: t-SNE Visualization (Non-Linear Mapping)')
plt.xlabel('t-SNE Dimension 1')
plt.ylabel('t-SNE Dimension 2')
plt.legend(title='Cluster', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(True, linestyle=':', alpha=0.4)
plt.show();
